name: App
options:
  bundleIdPrefix: com.bioprofar.app
configs:
  Release:
    type: release
targets:
  App:
    type: application
    platform: iOS
    sources:
      - .
    schemes:
      App:
        build:
          targets:
            App: all
        shared: true
